config/routes.rb
Rails.application.routes.draw do
  resources :employees
  resources :bicycles
  resources :orders
  root 'orders#index'
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bicycle.rb
# frozen_string_literal: true

class Bicycle < ApplicationRecord
  has_many :orders
  has_many :employees, through: :orders

  validates :manufacturer, :serial_number, presence: true, length: { minimum: 4, maximum: 20 }
end

app/models/employee.rb
# frozen_string_literal: true

class Employee < ApplicationRecord
  has_many :orders
  has_many :bicycles, through: :orders

  validates :name, :surname, presence: true, length: { minimum: 3, maximum: 20 }
end

app/models/order.rb
# frozen_string_literal: true

class Order < ApplicationRecord
  belongs_to :employee
  belongs_to :bicycle
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/bicycles_controller.rb
# frozen_string_literal: true

class BicyclesController < ApplicationController
  before_action :set_bicycle, only: %i[show edit update destroy]

  def show; end

  def index
    @bicycles = Bicycle.all
  end

  def new
    @bicycle = Bicycle.new
  end

  def edit; end

  def create
    @bicycle = Bicycle.new(bicycle_params)
    if @bicycle.save
      flash[:notice] = 'Bicycle was created successfully.'
      redirect_to bicycles_path
    else
      render 'new'
    end
  end

  def update
    if @bicycle.update(bicycle_params)
      flash[:notice] = 'Bicycle was updated successfully.'
      redirect_to bicycles_path
    else
      render 'edit'
    end
  end

  def destroy
    @bicycle.destroy
    flash[:notice] = 'Bicycle was deleted successfully.'
    redirect_to bicycles_path
  end

  private

  def set_bicycle
    @bicycle = Bicycle.find(params[:id])
  end

  def bicycle_params
    params.require(:bicycle).permit(:manufacturer, :serial_number)
  end
end

app/controllers/employees_controller.rb
# frozen_string_literal: true

class EmployeesController < ApplicationController
  before_action :set_employee, only: %i[show edit update destroy]

  def show; end

  def index
    @employees = Employee.all
  end

  def new
    @employee = Employee.new
  end

  def edit; end

  def create
    @employee = Employee.new(employee_params)

    if @employee.save
      flash[:notice] = 'Employee was created successfully.'
      redirect_to employees_path
    else
      render 'new'
    end
  end

  def update
    if @employee.update(employee_params)
      flash[:notice] = 'Employee was updated successfully.'
      redirect_to employees_path
    else
      render 'edit'
    end
  end

  def destroy
    @employee.destroy
    flash[:notice] = 'Employee was deleted successfully.'
    redirect_to employees_path
  end

  private

  def set_employee
    @employee = Employee.find(params[:id])
  end

  def employee_params
    params.require(:employee).permit(:name, :surname)
  end
end

app/controllers/orders_controller.rb
# frozen_string_literal: true

class OrdersController < ApplicationController
  before_action :set_order, only: %i[show edit update destroy]

  def show; end

  def index
    @orders = Order.all
  end

  def new
    @order = Order.new
  end

  def edit; end

  def create
    @order = Order.new(order_params)
    if @order.save
      flash[:notice] = 'Order was created successfully.'
      redirect_to orders_path
    else
      render 'new'
    end
  end

  def update
    if @order.update(order_params)
      flash[:notice] = 'Order was updated successfully.'
      redirect_to orders_path
    else
      render 'edit'
    end
  end

  def destroy
    @order.destroy
    flash[:notice] = 'Order was deleted successfully.'
    redirect_to orders_path
  end

  private

  def set_order
    @order = Order.find(params[:id])
  end

  def order_params
    params.require(:order).permit(:employee_id, :bicycle_id, :start_time, :end_time)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/views/bicycles/_form.html.haml
.row
  .col-10
    = render 'shared/errors', obj: @bicycle

    = form_with(model: @bicycle, class: 'shadow p-3 mb-3 bg-info rounded', local: true) do |f|
      .form-group.row
        .col-10
          = f.text_field :manufacturer, class: 'form-control shadow rounded', placeholder: 'Bycycle manufacturer'
      .form-group.row
        .col-10
          = f.text_field :serial_number, rows: 10, class: 'form-control shadow rounded', placeholder: 'Bycycle serial number'
      .form-group.row.justify-content-center
        = f.submit class: 'btn btn-outline-light btn-lg'

app/views/bicycles/edit.html.haml
%h1.my-3 Edit a new bicycle
= link_to 'Back to list', bicycles_path, class: 'btn btn-outline-primary mb-3'
= render 'form'

app/views/bicycles/index.html.haml
%h1.my-3 Bicycles list
= link_to 'Home', root_path, class: 'btn btn-outline-primary'
= link_to 'New bicycle', new_bicycle_path, class: 'btn btn-outline-success'

- unless @bicycles.nil?
  %table.table.table-striped.mt-4
    %tr
      %th manufacturer
      %th serial number
      %th action

    - @bicycles.each do |bicycle|
      %tr
        %td= bicycle.manufacturer
        %td= bicycle.serial_number
        %td
          = link_to 'Show', bicycle_path(bicycle), class: 'btn btn-outline-primary'
          = link_to 'Edit', edit_bicycle_path(bicycle), class: 'btn btn-outline-warning'
          - if bicycle.orders.length > 0
            %button.btn.btn-outline-danger{ disabled: 'disabled', type: 'button'} Delete bicycle*
          - else
            = link_to 'Delete bicycle', bicycle_path(bicycle), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-outline-danger'

  %p *delete all bicycle orders to delete bicycle

app/views/bicycles/new.html.haml
%h1.my-3 Create a new bicycle
= link_to 'Back to list', bicycles_path, class: 'btn btn-outline-primary mb-3'
= render 'form'

app/views/bicycles/show.html.haml
%h1.my-3
  = @bicycle.manufacturer
  = @bicycle.serial_number

= link_to 'Back to bicycles', bicycles_path, class: 'btn btn-outline-primary'

%h3.mt-3 Bicycle orders

%table.table.table-striped.mt-4
  %tr
    %th Id
    %th Employee
    %th Start time
    %th End time
    %th Action

  - @bicycle.orders.each do |order|
    %tr
      %td= order.id
      %td
        = Employee.find(order.employee_id).name
        = Employee.find(order.employee_id).surname
      %td= order.start_time.localtime.strftime('%Y/%m/%d %H:%M')
      %td= order.end_time.localtime.strftime('%Y/%m/%d %H:%M')
      %td
        = link_to 'Show', order_path(order), class: 'btn btn-outline-primary'
        = link_to 'Edit', edit_order_path(order), class: 'btn btn-outline-warning'
        = link_to 'Delete order', order_path(order), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-outline-danger'

= link_to 'Edit', edit_bicycle_path(@bicycle), class: 'btn btn-outline-warning'
- if @bicycle.orders.length > 0
  %button.btn.btn-outline-danger{ disabled: 'disabled', type: 'button'} Delete bicycle*
  %p.mt-3 *delete all employee orders to delete employee
- else
  = link_to 'Delete bicycle', bicycle_path(@bicycle), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-outline-danger'

app/views/employees/_form.html.haml
.row
  .col-10
    = render 'shared/errors', obj: @employee

    = form_with(model: @employee, class: 'shadow p-3 mb-3 bg-info rounded', local: true) do |f|
      .form-group.row
        .col-10
          = f.text_field :name, class: 'form-control shadow rounded', placeholder: 'Employee name'
      .form-group.row
        .col-10
          = f.text_field :surname, rows: 10, class: 'form-control shadow rounded', placeholder: 'Employee surname'
      .form-group.row.justify-content-center
        = f.submit class: 'btn btn-outline-light btn-lg'

app/views/employees/edit.html.haml
%h1.my-3 Edit a new employee
= link_to 'Back to list', employees_path, class: 'btn btn-outline-primary mb-3'
= render 'form'

app/views/employees/index.html.haml
%h1.my-3 Employees list

= link_to 'Home', root_path, class: 'btn btn-outline-primary'
= link_to 'New employee', new_employee_path, class: 'btn btn-outline-success'

- unless @employees.nil?
  %table.table.table-striped.mt-4
    %tr
      %th Name
      %th Surname
      %th Action

    - @employees.each do |employee|
      %tr
        %td= employee.name
        %td= employee.surname
        %td
          = link_to 'Show', employee_path(employee), class: 'btn btn-outline-primary'
          = link_to 'Edit', edit_employee_path(employee), class: 'btn btn-outline-warning'
          - if employee.orders.length > 0
            %button.btn.btn-outline-danger{ disabled: 'disabled', type: 'button'} Delete employee*
          - else
            = link_to 'Delete employee', employee_path(employee), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-outline-danger'

  %p *delete all employee orders to delete employee

app/views/employees/new.html.haml
%h1.my-3 Create a new employee
= link_to 'Back to list', employees_path, class: 'btn btn-outline-primary mb-3'
= render 'form'

app/views/employees/show.html.haml
%h1.my-3
  = @employee.name
  = @employee.surname

= link_to 'Back to employees', employees_path, class: 'btn btn-outline-primary'

%h3 Employee orders

%table.table.table-striped.mt-4
  %tr
    %th Id
    %th Bicycle
    %th Start time
    %th End time
    %th Action

  - @employee.orders.each do |order|
    %tr
      %td= order.id
      %td
        = Bicycle.find(order.bicycle_id).manufacturer
        = Bicycle.find(order.bicycle_id).serial_number
      %td= order.start_time.localtime.strftime('%Y/%m/%d %H:%M')
      %td= order.end_time.localtime.strftime('%Y/%m/%d %H:%M')
      %td
        = link_to 'Show', order_path(order), class: 'btn btn-outline-primary'
        = link_to 'Edit', edit_order_path(order), class: 'btn btn-outline-warning'
        = link_to 'Delete order', order_path(order), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-outline-danger'

= link_to 'Edit', edit_employee_path(@employee), class: 'btn btn-outline-warning'
- if @employee.orders.length > 0
  %button.btn.btn-outline-danger{ disabled: 'disabled', type: 'button'} Delete employee*
  %p.mt-3 *delete all employee orders to delete employee
- else
  = link_to 'Delete employee', employee_path(@employee), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-outline-danger'

app/views/layouts/_messages.html.haml
- flash.each do |name, msg|
  %div.mt-4{ class: "alert alert-#{name == 'notice' ? 'success' : 'danger'} alert-dismissible fade show", role: 'alert'}
    = msg
    %button.close{ aria: { label: 'Close' }, data: { dismiss: 'alert' }, type: 'button' }
      %span{ aria: { hidden: 'true' } } ×

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{ content: 'text/html; charset=UTF-8', 'http-equiv' => 'Content-Type' }/
    %title Orders
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    .container
      = render 'layouts/messages'
      = yield

app/views/orders/_form.html.haml
.row
  .col-10
    = render 'shared/errors', obj: @order

    = form_with(model: @order, class: 'shadow p-3 mb-3 bg-info rounded', local: true) do |f|
      .form-group.row
        .col-10
          = f.collection_select(:employee_id, Employee.all, :id, :surname, { prompt: 'Select employee'})
      .form-group.row
        .col-10
          = f.collection_select(:bicycle_id, Bicycle.all, :id, :manufacturer, { prompt: 'Select bicycle'})
      .form-group.row
        .col-10
          Select start date and time
        .col-10
          = f.datetime_select :start_time
      .form-group.row
        .col-10
          Select end date and time
        .col-10
          = f.datetime_select :end_time, class: 'form-control'
      .form-group.row.justify-content-center
        = f.submit class: 'btn btn-outline-light btn-lg'

app/views/orders/edit.html.haml
%h1.my-3 Edit order
= link_to 'Back to list', orders_path, class: 'btn btn-outline-primary mb-3'
= render 'form'

app/views/orders/index.html.haml
%h1.my-3 Order list

= link_to 'Employees', employees_path, class: 'btn btn-outline-primary'
= link_to 'Bicycles', bicycles_path, class: 'btn btn-outline-primary'
= link_to 'New order', new_order_path, class: 'btn btn-outline-success'

- unless @orders.nil?
  %table.table.table-striped.mt-4
    %tr
      %th Id
      %th Employee
      %th Bicycle
      %th Start time
      %th End time
      %th Action

    - @orders.each do |order|
      %tr
        %td= order.id
        %td
          = Employee.find(order.employee_id).name
          = Employee.find(order.employee_id).surname
        %td
          = Bicycle.find(order.bicycle_id).manufacturer
          = Bicycle.find(order.bicycle_id).serial_number
        %td= order.start_time.localtime.strftime('%Y/%m/%d %H:%M')
        %td= order.end_time.localtime.strftime('%Y/%m/%d %H:%M')
        %td
          = link_to 'Show', order_path(order), class: 'btn btn-outline-primary'
          = link_to 'Edit', edit_order_path(order), class: 'btn btn-outline-warning'
          = link_to 'Delete', order_path(order), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-outline-danger'

app/views/orders/new.html.haml
%h1.my-3 Create a new order
= link_to 'Back to list', orders_path, class: 'btn btn-outline-primary mb-3'
= render 'form'

app/views/orders/show.html.haml
%h1.my-3
  Order number
  = @order.id

= link_to 'Back', orders_path(), class: 'btn btn-outline-primary'

%table.table.table-striped.mt-4
  %tr
    %td Employee:
    %td
      = Employee.find(@order.employee_id).name
      = Employee.find(@order.employee_id).surname
  %tr
    %td Bicycle:
    %td
      = Bicycle.find(@order.bicycle_id).manufacturer
      = Bicycle.find(@order.bicycle_id).serial_number
  %tr
    %td Start time:
    %td= @order.start_time.localtime.strftime('%d/%m/%Y %H:%M')
  %tr
    %td End time:
    %td= @order.end_time.localtime.strftime('%d/%m/%Y %H:%M')

= link_to 'Edit', edit_order_path(@order), class: 'btn btn-outline-warning'
= link_to 'Delete', order_path(@order), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-outline-danger'

app/views/shared/_errors.html.haml
- if obj.errors.any?
  .alert.alert-danger.alert-dismissible.fade.show{ role: 'alert' }
    %h4.alert-heading
      The following errors prevented the #{obj.class.name.downcase} from being saved
    %ul
      - obj.errors.full_messages.each do |msg|
        %li= msg
    %button.close{ aria: { label: 'Close' }, data: { dismiss: 'alert' }, type: 'button' }
      %span{ aria: { hidden: 'true' } } ×